### ISSUE TITLE
Todo list before 1.0 release

### ISSUE THREAD

**Issue by Danielv123** [Danielv123/gridworld#1]
These are features I want working before 1.0 release:

- [x] One click gridworld creation
- [x] Gridworld minimap
- [x] - render entities on map
- [x] #14
- [x] Dynamically create servers as players move about
- [x] Show players on minimap
- [x] #13 
- [x] #7
